#!/bin/bash

# tacc specific 

repo=/root/Jetstream-Salt-States
privrepo=/root

mkdir -p /srv/pillar
rsync -avx $repo/pillar/ /srv/pillar

mkdir -p /srv/salt
rsync -avx $repo/states/ /srv/salt

cp -f $privrepo/passwords.sls /srv/pillar
cp -f $privrepo/vars.sls /srv/pillar

rsync -avx $privrepo/ceph-config /srv/salt/ceph
