mysqlhost: 172.16.128.2
rabbit_hosts: 172.16.128.253,172.16.128.252,172.16.128.250
keystonehost: jblb.jetstream-cloud.org
keystonepublichost: jblb.jetstream-cloud.org
glancepublichost: jblb.jetstream-cloud.org
glanceprivatehost: jblb.jetstream-cloud.org 
cinderpublichost: jblb.jetstream-cloud.org
cinderprivatehost: jblb.jetstream-cloud.org
novapublichost: jblb.jetstream-cloud.org
novaprivatehost: jblb.jetstream-cloud.org
novametadatahost: 172.16.128.2 
neutronpublichost: jblb.jetstream-cloud.org
neutronprivatehost: jblb.jetstream-cloud.org
ceilometerpublichost: jblb.jetstream-cloud.org
ceilometerprivatehost: jblb.jetstream-cloud.org
gnocchi_url: https://jblb.jetstream-cloud.org:8041
heathost: jblb.jetstream-cloud.org
muranoprivatehost: jblb.jetstream-cloud.org
